### ISSUE TITLE
authentication when using docker workers

### ISSUE THREAD

**Issue by williewonka** [ufora/ufora#108]
Hello,

I was wondering what kind of authentication is possible when using a docker worker. Would it be possible to use ufora on a whole cluster of dockerimages that are running on different machines? what kind of authentication would be used in that case?

**Comment by ronenh** [comment]
What sort of authentication scenario do you have in mind? The backend has no auth model at this time, and really has no notion of "users" - if you have network access to the cluster you can submit work.

When running a cluster in the cloud (AWS for example) you can configure your network so that Ufora instances are only reachable from other Ufora instances. To connect to the manager instance from your `pyfora` client, you can use SSH to tunnel Ufora's HTTP port (30000 by default). Only users who can SSH into your instance will be able to use the cluster.

If you are asking about sharing a Ufora cluster between multiple users (locally or in the cloud) and managing access, then that's a feature we have not implemented yet. It is somewhere in our roadmap, but not an immediate priority.

**Comment by williewonka** [comment]
i mean if you have several machines each running multiple docker workers how do you prevent unauthorized access to them. ssh proxy is the best way to go it seems from your answer?

**Comment by ronenh** [comment]
You should be aware that your client machine, where you use `pyfora` to submit work to the Ufora cluster doesn't need access to *all* the workers. When running Ufora in a cluster, you designate one machine as the cluster-manager and that is the only machine the you need to connect to in order to interact with the cluster. In addition to (optionally) running the ufora-worker service, the manager runs a couple of additional processes, including the HTTP server that `pyfora` talks to.

The manager *does* need to be able to talk to all workers, and they need to be able to talk to each other but no-one outside the cluster ever talks to workers directly.
This may mean, depending on your setup, that you can protect workers from unwanted access using firewall rules, and control access to the manager using SSH.

Does that help clarify things a bit?

**Comment by williewonka** [comment]
ah ok yes that clarifies it. so for example i can have machine A with a cluster of workers plus the management thing and machine B with additional workers. But how do i than configure the workers on machine B to talk to the workers on machine A? ssh tunnel and firewall rules can indeed work for this.

**Comment by ronenh** [comment]
It's not 100% clear to me what machines A and B are. However:

If machines A and B represent two separate users who want to submit work independently of each other without sharing any workers, then what you probably want are two separate clusters, each with its own manager+workers.

If, on the other hand, you are thinking of A and B as hosts that run a bunch of Ufora docker containers, I would question why you want to run more than one container per box. The reason I ask this is that a ufora-worker, by default, is going to use all CPU cores available to run computations in parallel. A second worker on the same machine is only going to compete with the first one for resources.
If you have a large machine with many cores and you want to share it between two users, it is possible to configure the max number of cores used by a Ufora worker. But if both workers are going to be part of the same cluster (i.e. both connect to the same manager) you will probably be better off running a single worker on all cores.

**Comment by williewonka** [comment]
No i want one user to be able to send workload to a cluster of workers which are divided over multiple machines ( in my example machine A and machine B). So one docker worker on machine A and one on machine B.

I think the use case i'm trying to (badly, im sorry) explain is this https://ufora.github.io/ufora/content/tutorials/getting-started-cluster.html but that doc link seems to be not filled atm.
From your answer it seems i need to run one docker container on each of my cluster machines but im confused as to how to set this up correctly (and secure).

**Comment by ronenh** [comment]
Got it! That makes total sense. And apologies for the incomplete documentation - we are actively working on filling in the gaps...

There are several environment variables you can pass in to the Ufora container when you `docker run` it:

- `UFORA_MANAGER_ADDRESS`: the host-name or IP address of the Ufora manager. Setting this variable causes the container to only run the worker service. If this variable is not specified, the container will run **both** manager and worker services.
- `UFORA_WORKER_OWN_ADDRESS`: the host-name or IP address that the Ufora worker uses to publish itself. Other workers will try to connect to it using this address. This is useful in situations where you have multiple network interfaces (public and private, or a docker container running in bridge mode) and you want to tell the worker which address to advertise.
- `UFORA_NO_WORKER`: Set this variable to `1` to prevent the manager container from also running a worker.

I *think* that's all you need in order to set-up a simple multi-machine cluster.

**Comment by williewonka** [comment]
Ok thankyou that is indeed what i meant. still one small thing, the UFORA_WORKER_OWN_ADDRESS is the address of the manager to which the worker will register itself too? Or hostname of itself, in which case im confused by how the worker knows where the manager is.

**Comment by ronenh** [comment]
The value in `UFORA_MANAGER_ADDRESS` tells the worker where the manager is.

The value in `UFORA_WORKER_OWN_ADDRESS` tells the worker its *own* address. This value is optional and if it isn't specified, the worker will try to figure our its own address using `socket.gethostbyname(socket.getfqdn())`.

**Comment by ronenh** [comment]
Docs updated: [Setting up a Ufora Cluster](http://ufora.github.io/ufora/content/tutorials/03-getting-started-cluster.html)

**Comment by williewonka** [comment]
great thanks!
