### ISSUE TITLE
Failure when trying to convert a list of mapped functions

### ISSUE THREAD

**Issue by Amichai** [ufora/ufora#120]
Converts, no problem:
```
        def a():
            x = [len]
            return x
```
Fails to convert:
```
        x = [len]
        def a():
            return x
```

Specifically, I'm seeing a mysterious KeyError:

```
Traceback (most recent call last):
  File "/volumes/ufora/ufora/FORA/python/PurePython/ExecutorTestCases.py", line 665, in test_mapped_function
    r = self.evaluateWithExecutor(a)
  File "/volumes/ufora/ufora/FORA/python/PurePython/ExecutorTestCases.py", line 56, in evaluateWithExecutor
    raise ex
KeyError: 140516507768952

```

**Comment by tdp2110** [comment]
The problem is in the second phase of `ObjectVisitors.walkPythonObject`: the `ObjectVisitor` class. The list `x` gets replaced (`PyObjectWalker._objectToWalkInsteadOrNone`) by a `PyObjectNodes.ClassInstanceDescription` _holding `len` itself_ in its `classMemberNameToMemberValue` dict. When we assigned ids in the first pass, the `PyObjectWalker` recursed on this dict, and replaced `len` with its mappable type (from `BuiltinPureImplemenationMappings`), so we assigned an id to `BuiltinPureImplementationMappings.Len` and _not_ to `len`. When the second phase `ObjectVisitor` encounters this `ClassInstanceDescription` (for the list), he tries to look up the registered id for `len`, _not_ `Len`.

**Comment by tdp2110** [comment]
This is in general a problem for any datastructure holding a mappable type, as I saw in attempting to map dataframes.

**Comment by tdp2110** [comment]
One way to deal with this would be to get rid of the confusing `_objectToWalkInsteadOrNone` stuff by first doing an explicit transform phase on all python objects getting fed into `ObjectVisitors.walkPythonObject` to get them once and for all into the form we like for the rest of the walks/visits.

**Comment by braxtonmckee** [comment]
I would be in favor of this. In general, I find that code hard to
understand because its doing several things at once.  It would be better to
first build a translated representation of the object graph, and then
decide how to send that over. This would also give us a coherent model for
caching, since right now we don't cache anything, which is very expensive.

On Thu, Nov 12, 2015 at 2:22 PM, Thomas Peters <notifications@github.com>
wrote:

> One way to deal with this would be to get rid of the confusing
> _objectToWalkInsteadOrNone stuff by first doing an explicit transform
> phase on all python objects getting fed into
> ObjectVisitors.walkPythonObject to get them once and for all into the
> form we like for the rest of the walks/visits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/120#issuecomment-156207699>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
sounds good. I'm on it

On Thu, Nov 12, 2015 at 2:39 PM, Braxton McKee <notifications@github.com>
wrote:

> I would be in favor of this. In general, I find that code hard to
> understand because its doing several things at once. It would be better to
> first build a translated representation of the object graph, and then
> decide how to send that over. This would also give us a coherent model for
> caching, since right now we don't cache anything, which is very expensive.
>
> On Thu, Nov 12, 2015 at 2:22 PM, Thomas Peters <notifications@github.com>
> wrote:
>
> > One way to deal with this would be to get rid of the confusing
> > _objectToWalkInsteadOrNone stuff by first doing an explicit transform
> > phase on all python objects getting fed into
> > ObjectVisitors.walkPythonObject to get them once and for all into the
> > form we like for the rest of the walks/visits.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufora/ufora/issues/120#issuecomment-156207699>.
> >
>
>
>
> --
>
> -------------------------------------------------------------------------------------------
> Braxton McKee CEO / Ufora
> www.twitter.com/braxtonmckee www.ufora.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/120#issuecomment-156211797>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com
