### ISSUE TITLE
Other Language Front Ends

### ISSUE THREAD

**Issue by sirinath** [ufora/ufora#148]
Can you support other language front ends, as well as, ByteCode, IR, IL conversions.

Languages your can support:

 - R
 - Julia
 - Spreadsheets
 - JVM ByteCode
 - .Net
 - LLVM IR

In case of IR, IL, ByteCode you need to do something like what https://www.maxeler.com/ employees to parallelise.

Maybe you can use a framework like https://srclib.org/ or another framework to gt multiple front ends working.

**Comment by braxtonmckee** [comment]
Hi Suminda,

I think we are planning on doing R next, as soon as we get enough of the
core python functionality in place to support the use-cases we care about.
Julia would be a natural fit, I think, although probably less of a priority
since Julia already has a very good jit.

We've considered JVM/CLR bytecode, but generally speaking it's probably
better to do these transformations at a higher level (e.g. in scala or c#
as the case depends) since more of the original language semantics are
still present. I think LLVM IR is probably not a good candidate - so much
of the original semantic structure of the program has been stripped away
(and replaced with direct memory operations) at that point that there's
very little for the UFORA VM to work with.

On Wed, Nov 25, 2015 at 12:13 AM, Suminda Dharmasena <
notifications@github.com> wrote:

> Can you support other language front ends, as well as, ByteCode, IR, IL
> conversions.
>
> Languages your can support:
>
>    - R
>    - Julia
>    - JVM ByteCode
>    - .Net
>    - LLVM IR
>
> In case of IR, IL, ByteCode you need to do something like what
> https://www.maxeler.com/ employees.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/148>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by sirinath** [comment]
With LLVM, Native code you just have to reverse engine as so far as to get ad workable AST / TST with effects and proofs to re optimise.

**Comment by braxtonmckee** [comment]
I agree that's what you'd need to do, but why bother? All LLVM code comes
from some other language, so for most use cases, I'd think it would make
more sense to start at the source language.  In any case, I don't think
it's a high-priority use case compared to optimizing programs written in R,
python, or some other high-level language people actually use to do data
science.

Again, as this is not really an "issue", and more of a discussion of
possible future directions of Ufora, I'd ask that we take this conversation
to the ufora-dev or ufora-user mailing list.

On Wed, Nov 25, 2015 at 1:22 PM, Suminda Dharmasena <
notifications@github.com> wrote:

> With LLVM, Native code you just have to reverse engine as so far as to get
> ad workable AST / TST with effects and proofs to re optimise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/148#issuecomment-159693519>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
