### ISSUE TITLE
free variable blowups could have better messages

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#90]
for example if you try to work with

    def f():
        return x

you'll get a message like `PythonToForaConversionError: don't know how to resolve ('x',) in <function f at 0x7fb05320b1b8>`. 

first point: we could say the line number of `f`. 

Second point, you'll see the same message for

    def f(arg):
        if arg:
            x = 42
        return x

Here `x` isn't really free, but it's possibly uninitialized, and we puke on that, but we don't explain that this is the problem.

THIRD point, if you do:

    def f():
        return x.y.z

I bet you'll get the message `PythonToForaConversionError: don't know how to resolve ('x', 'y', 'z') in <function f at 0x7fb05320b1b8>`. It's not clear what this means except for people deep in the trenches.

**Comment by atzannes** [comment]
hm... ok I will be careful to not use this syntax for commits that I rebase, overwrite etc...

**Comment by atzannes** [comment]
Ok @tdp2110 this is the finalized fix. Since, you recently rewrote the PyObjectWalker and made a lot of changes to that, could you take a look and let me know if things look good?

**Comment by atzannes** [comment]
@tdp2110 in the commit listed above I addressed the comment about using namedtuples and I reintroduced the cached decorator on the getAstFromText function and opened an issue for refactoring some of these functions in PyAstUtil. I looked around for an alternative way to terminate a visitation early but didn't find something useful. Let me know if the new commit looks good, and pending the looper I'll push to dev (after squashing the commits so that we won't have a commit that fails tests).
